### ISSUE TITLE
Selector query not functioning properly

### ISSUE THREAD

**Issue by ghost** [wearetheledger/go-couchdb-query-engine#1]
I tried running a simple selector query, but it is not functioning as it should. Please find code snippet below:

**main.go**
```
package main

import (
	"fmt"

	query "github.com/wearetheledger/go-couchdb-query-engine/query"
)

func main() {
	var TestData = map[string]interface{}{
		"tradingSymbol:APPL": map[string]interface{}{
			"description":   "Apple",
			"docType":       "commodity",
			"mainExchange":  "NASDAQ",
			"quantity":      "1000",
			"traderId":      "aldred",
			"tradingSymbol": "APPL",
		},
		"tradingSymbol:HPE": map[string]interface{}{
			"description":   "Hewlett Packard Enterprise",
			"docType":       "commodity",
			"mainExchange":  "NASDAQ",
			"quantity":      "2500",
			"traderId":      "janis",
			"tradingSymbol": "HPE",
		},
		"tradingSymbol:IBM": map[string]interface{}{
			"description":   "IBM",
			"docType":       "commodity",
			"mainExchange":  "NASDAQ",
			"quantity":      "5000",
			"traderId":      "aldred",
			"tradingSymbol": "IBM",
		},
	}

	res, err := query.ParseCouchDBQuery(TestData, map[string]interface{}{
		"selector": map[string]interface{}{
			"docType": map[string]interface{}{
				"$eq": "commodity",
			},
			"traderId": map[string]interface{}{
				"$eq": "aldred",
			},
		},
	})

	if err != nil {
		fmt.Println(err.Error())
	}

	fmt.Println(res)
}
```

I received the wrong output. the stock with **traderId:janis** should not be listed
`[{tradingSymbol:APPL map[mainExchange:NASDAQ quantity:1000 traderId:aldred tradingSymbol:APPL description:Apple docType:commodity]} {tradingSymbol:HPE map[traderId:janis tradingSymbol:HPE description:Hewlett Packard Enterprise docType:commodity mainExchange:NASDAQ quantity:2500]} {tradingSymbol:IBM map[quantity:5000 traderId:aldred tradingSymbol:IBM description:IBM docType:commodity mainExchange:NASDAQ]}]`

I tried to run the query in real couchdb and it works as expected:
![image](https://user-images.githubusercontent.com/21098213/41443740-de96ac52-7068-11e8-8f39-ab3defe6de6f.png)

Proof that there is a total of 3 documents:
![image](https://user-images.githubusercontent.com/21098213/41443759-f8911656-7068-11e8-9086-212136029721.png)

This is my version:

**vendor.yml**
```
vendors:
- path: github.com/wearetheledger/go-couchdb-query-engine
  rev: 0608ed73ba650731c085a1defcff3eede8e6dda7
```

**Comment by ghost** [comment]
I tried this and it works. However, when I integrate in my Hyperledger Fabric project to run my unit tests, I get this error when running the unit test:

```
Running tool: /usr/local/bin/go test -timeout 30s blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode -run ^TestCreateDummyData$

As an admin, I am able to create dummy data for testing purposes
2018-06-19 06:52:42.590 WIB [commodity_native] Info -> INFO 001[0m ########### Init Start ###########
2018-06-19 06:52:42.590 WIB [commodity_native] Info -> INFO 002[0m ########### Init End ###########
2018-06-19 06:52:42.590 WIB [commodity_native] Info -> INFO 003[0m ########### Invoke create_trader ###########
2018-06-19 06:52:42.591 WIB [commodity_native] Infof -> INFO 004[0m [CreateTrader] Invoked by: aldred
2018-06-19 06:52:42.591 WIB [commodity_native] Info -> INFO 005[0m ########### Invoke create_trader ###########
2018-06-19 06:52:42.591 WIB [commodity_native] Infof -> INFO 006[0m [CreateTrader] Invoked by: janis
2018-06-19 06:52:42.591 WIB [commodity_native] Info -> INFO 007[0m ########### Invoke create_commodity ###########
2018-06-19 06:52:42.591 WIB [commodity_native] Infof -> INFO 008[0m [CreateCommodity] Invoked by: aldred
2018-06-19 06:52:42.591 WIB [commodity_native] Info -> INFO 009[0m ########### Invoke create_commodity ###########
2018-06-19 06:52:42.591 WIB [commodity_native] Infof -> INFO 00a[0m [CreateCommodity] Invoked by: aldred
2018-06-19 06:52:42.591 WIB [commodity_native] Info -> INFO 00b[0m ########### Invoke create_commodity ###########
2018-06-19 06:52:42.591 WIB [commodity_native] Infof -> INFO 00c[0m [CreateCommodity] Invoked by: janis
2018-06-19 06:52:42.591 WIB [commodity_native] Info -> INFO 00d[0m ########### Invoke get_commodities_by_trader ###########
{"selector":{"docType":"commodity","traderId":"aldred"},"use_index":"_design/commoditiesTraderDoc"}
--- FAIL: TestCreateDummyData (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x447d91e]

goroutine 20 [running]:
testing.tRunner.func1(0xc4203580f0)
    /usr/local/opt/go/libexec/src/testing/testing.go:742 +0x29d
panic(0x4590a80, 0x4a20ee0)
    /usr/local/opt/go/libexec/src/runtime/panic.go:502 +0x229
blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/vendor/github.com/wearetheledger/go-couchdb-query-engine/query/rules.eq.Match(0x4648b6d, 0x3, 0x0, 0x0, 0x4555d80, 0xc4203839a0, 0x44837cc, 0x4555d80, 0xc420383a70)
    /Users/aldred/Workspace/go/src/blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/vendor/github.com/wearetheledger/go-couchdb-query-engine/query/rules/eq.go:11 +0x5e
blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/vendor/github.com/wearetheledger/go-couchdb-query-engine/query.test(0x0, 0x0, 0x4555d80, 0xc4203839a0, 0x4a579e0, 0xc420383a70, 0x1)
    /Users/aldred/Workspace/go/src/blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/vendor/github.com/wearetheledger/go-couchdb-query-engine/query/query.go:199 +0x48d
blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/vendor/github.com/wearetheledger/go-couchdb-query-engine/query.test(0x45899a0, 0xc42035f5c0, 0x45899a0, 0xc42035f620, 0xc420390628, 0x0, 0x0)
    /Users/aldred/Workspace/go/src/blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/vendor/github.com/wearetheledger/go-couchdb-query-engine/query/query.go:180 +0x2b2
blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/vendor/github.com/wearetheledger/go-couchdb-query-engine/query.ParseCouchDBQueryString(0xc4201093c0, 0xc420326c40, 0x63, 0xf, 0xc420109518, 0x0, 0x0, 0x4083d83)
    /Users/aldred/Workspace/go/src/blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/vendor/github.com/wearetheledger/go-couchdb-query-engine/query/query.go:94 +0x2d9
blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/core/chaincode/shim.(*CustomMockStub).GetQueryResult(0xc420310e80, 0xc420326c40, 0x63, 0x64, 0x0, 0x0, 0x63)
    /Users/aldred/Workspace/go/src/blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/core/chaincode/shim/custom_mockstub.go:142 +0x227
blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode.(*Commodity).GetCommodityByTrader(0xc4203148f0, 0x46ce0e0, 0xc420310e80, 0xc420381f70, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/aldred/Workspace/go/src/blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/commodity.go:221 +0x228
blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode.(*CommodityChaincode).Invoke(0xc4203148f0, 0x46ce0e0, 0xc420310e80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/aldred/Workspace/go/src/blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/main.go:64 +0x840
blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/core/chaincode/shim.(*CustomMockStub).MockInvoke(0xc420310e80, 0x4661893, 0x24, 0xc42035f4a0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/aldred/Workspace/go/src/blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/vendor/github.com/hyperledger/fabric/core/chaincode/shim/custom_mockstub.go:93 +0xcc
blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode.query(0xc4203580f0, 0xc420310e80, 0xc42035f4a0, 0x2, 0x2, 0x4670915, 0x119, 0x0)
    /Users/aldred/Workspace/go/src/blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/main_test.go:59 +0x7f
blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode.TestCreateDummyData(0xc4203580f0)
    /Users/aldred/Workspace/go/src/blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode/main_test.go:119 +0xed9
testing.tRunner(0xc4203580f0, 0x4676020)
    /usr/local/opt/go/libexec/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
    /usr/local/opt/go/libexec/src/testing/testing.go:824 +0x2e0
FAIL    blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode    0.033s
Error: Tests failed.
```

I reverted back to the previous version (0608ed73ba650731c085a1defcff3eede8e6dda7) and I did not encounter such messages (although query result is still incorrect)

```
Running tool: /usr/local/bin/go test -timeout 30s blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode -run ^TestCreateDummyData$

As an admin, I am able to create dummy data for testing purposes
2018-06-19 06:54:37.870 WIB [commodity_native] Info -> INFO 001[0m ########### Init Start ###########
2018-06-19 06:54:37.870 WIB [commodity_native] Info -> INFO 002[0m ########### Init End ###########
2018-06-19 06:54:37.870 WIB [commodity_native] Info -> INFO 003[0m ########### Invoke create_trader ###########
2018-06-19 06:54:37.871 WIB [commodity_native] Infof -> INFO 004[0m [CreateTrader] Invoked by: aldred
2018-06-19 06:54:37.871 WIB [commodity_native] Info -> INFO 005[0m ########### Invoke create_trader ###########
2018-06-19 06:54:37.871 WIB [commodity_native] Infof -> INFO 006[0m [CreateTrader] Invoked by: janis
2018-06-19 06:54:37.871 WIB [commodity_native] Info -> INFO 007[0m ########### Invoke create_commodity ###########
2018-06-19 06:54:37.871 WIB [commodity_native] Infof -> INFO 008[0m [CreateCommodity] Invoked by: aldred
2018-06-19 06:54:37.871 WIB [commodity_native] Info -> INFO 009[0m ########### Invoke create_commodity ###########
2018-06-19 06:54:37.871 WIB [commodity_native] Infof -> INFO 00a[0m [CreateCommodity] Invoked by: aldred
2018-06-19 06:54:37.871 WIB [commodity_native] Info -> INFO 00b[0m ########### Invoke create_commodity ###########
2018-06-19 06:54:37.871 WIB [commodity_native] Infof -> INFO 00c[0m [CreateCommodity] Invoked by: janis
2018-06-19 06:54:37.871 WIB [commodity_native] Info -> INFO 00d[0m ########### Invoke get_commodities_by_trader ###########
{"selector":{"docType":"commodity","traderId":"aldred"},"use_index":"_design/commoditiesTraderDoc"}
res.Payload: {"count": 3, "data":[{"docType":"commodity","tradingSymbol":"APPL","description":"Apple","mainExchange":"NASDAQ","quantity":"1000","traderId":"aldred"},{"docType":"commodity","tradingSymbol":"HPE","description":"Hewlett Packard Enterprise","mainExchange":"NASDAQ","quantity":"2500","traderId":"janis"},{"docType":"commodity","tradingSymbol":"IBM","description":"IBM","mainExchange":"NASDAQ","quantity":"5000","traderId":"aldred"}]}
Query get_commodities_by_trader did not match expected result:  {"count": 2, "data":[{"docType":"commodity","tradingSymbol":"IBM","description":"IBM","mainExchange":"NASDAQ","quantity":"5000","traderId":"aldred"},{"docType":"commodity","tradingSymbol":"APPL","description":"Apple","mainExchange":"NASDAQ","quantity":"1000","traderId":"aldred"}]}
--- FAIL: TestCreateDummyData (0.00s)
FAIL
FAIL    blockchain-commodity-backend/commodity-network/chaincode/commodity-chaincode    0.028s
Error: Tests failed.
```
I'm not sure if I need to create a separate issue for this.

To reproduce the error, go to: https://git.ng.bluemix.net/blockchain-training/blockchain-commodity-backend#1-setup-local-environment-mac-os-ubuntu and follow that section until you run the command `go test`

**Comment by sneljo1** [comment]
@caveman7 This issue has now been fixed. 🎉

**Comment by ghost** [comment]
Thanks @Superjo149 . It works now. I hope it can be integrated in Hyperledger Fabric base code soon
